#!/bin/bash
./lolban BuildLinux | pv -q -L 700
wait
sleep 3
wait
sleep 1
echo dowloading linux-kernel
sleep 5
wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.0.7.tar.xz
wait 
echo unpacking archive
sleep 1
tar xvfJ  linux-5.0.7.tar.xz
sleep 2
echo installing requirements
sleep 4
sudo apt  install   kernel-package fakeroot  libncursesw5-dev libssl-dev bison flex
wait
sleep 1
echo going into kernel directory
sleep 1
cd linux-5.0.7
sleep 1
read -p "Press enter to build kernel"
echo making menuconfig
sleep 2
sudo make menuconfig 
wait
sleep 2
sudo fakeroot make-kpkg -j 5 --initrd --append-to-version=-custom kernel_image kernel_headers #-j
wait
sleep 2
echo "Kernel compiled"
